apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
        - name: front-end
          image: mouliveleti/microservices:eventbus

---

apiVersion: v1
kind: Service
metadata:
  name: eventbus-serv
spec:
  type: ClusterIP
  selector:
    app: eventbus
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005