apiVersion: skaffold/v2alpha3
king: Config
deploy: 
    kubctl: 
      manifests:
        - ./infra/k8s/*
build:
    local:
      push: false
    artifacts:
      - image: mouliveleti/client
        context: postandcomments
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: 'src/**/*.js'
              dest: .
